= Analyse du domaine
 
== Introduction

=== Objectif

// Décrire l'objectif de ce chapitre.

Ce chapitre constitue le premier livrable d’une série de quatre chapitres destinés à fournir une analyse et une conception par objets complètes répondant au cahier des charges qui nous a été fourni. 
Ce document présente l’ensemble de la démarche suivie ainsi que les résultats obtenus lors de la phase de l'analyse du domaine de notre système. 
Il se décompose en plusieurs parties.

Dans la première partie, nous présentons de manière détaillée l’ensemble des cas d’utilisation que nous avons dégagés lors de l’analyse. 
Nous utiliserons pour cela le canevas proposé par Cockburn que nous compléterons par des instantanés ainsi que par des post-conditions exprimées en OCL (Object Constraint Language) et quelques scenarii. 
Cette partie constitue une étape clé de la phase de l'analyse du domaine.

Dans la deuxième partie, nous présentons le  diagramme de classes métiers (i.e. diagramme de classes au niveau analyse) que nous avons construit à partir de l’analyse réalisée. 
Ce diagramme fournit une vue statique et synthétique du domaine de notre projet. 
Cette  partie constitue également une étape clé de la phase de spécification des besoins.


Dans la troisième er dernière nous fournissons le dictionnaire des données que nous avons construit suite à l'analyse du domaine. 
Il s’agit d’un listing de l’ensemble des termes relatifs au domaine étudié ainsi que leur définition précise.



Dans une quatrième et dernière partie, 

=== Organisation du chapitre

Ce chapitre est organisé en $n$ sections. Dans le première section, nous décrirons....



== Cas d'utilisation

=== Mise en place d'un jeu

*Use Case :* Initialisation 3 joueurs ou plus  

*Id :* 	UC#1

*Description :* Initialisation du jeu quand il y a entre 3 et 6 joueurs

*Pre-Conditions :* il y a entre 3 et 6 joueurs, les joueurs sont près, il y a une pioche de 44 cartes risk et 14 cartes missions disponnible, il y a 5 dés disponnibles.

*Scénario nominal :*

. On retire de la pioche de 44 carte risk les 2 cartes joker +
. On distribue 1 carte risk a un joueur +
. On passe au joueur suivant + 
_les étapes 2 et 3 sont répétées tant qu'il reste des cartes risk._ +
[Start = 4]
. Les cartes risk sont retournées dans la pioche +
. Les joueurs pioches un certain nombre de fantassin +
. Un joueur dépose 1 fantassin sur chaque pays qu'il possède + 
_l'étape 6 est répété pour chaque joueur_ +
[Start = 7]
. Une carte mission est distribué a un joueur + 
_l'étape 7 est répété pour chaque joueur_ + 
[Start = 8]
. On tire au hasard le premier joueur +
. Le joueur pose un fantassin sur un territoire qu'il possède. +
. Passage au joueur suivant + 
_les étapes 9 et 10 sont répété tant qu'il reste un joueur avec des fantassins à poser_ +
[Start = 11]
. Le premier joueur commence UC#3 +

*Extension :*

[start = 5]
. Chaque joueur pioche (35-5 * (nombre_de_joueur-3))

[start = 7]
. Une mission portant sur la destruction de l'armée d'un joueur +
	.. Cette mission doit visé un joueur présent sur le plateau +
	.. Cette mission ne peut pas visé le joueur l'ayant reçu +

*Post-Conditions :*

Toutes les cartes territoires on été distribuée, Les joueurs ont posé tous leur fantassin de départ, Chaque joueur a une et une seul mission

== Modèle de classes du domaine

[plantuml, domain-classes, png]
----
@startuml
Class01 <|-- Class02
Class03 *-- Class04
Class05 o-- Class06
Class07 .. Class08
Class09 -- Class10
@enduml
----

=== Invariants

[source,ocl]
----
context Etudiant::age() : Integer
post correct: result = (today - naissance).years()

context Typename::operationName(param1: type1, ...): Type
post: result = ...

context Typename::operationName(param1: type1, ...): Type
post resultOk: result = ...
----


== Dictionnaire de données
	
include::terms.adoc[]


== Conclusion

